### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by Burtan** [dellisd/sqldelight-sqlite-wasm#1]
Hey,
I tried your example, however it does not work, currently (Linux firefox and chrome). 
https://dellisd.github.io/sqldelight-sqlite-wasm/

`sqlite3.js:9978 Ignoring inability to install OPFS sqlite3_vfs: This environment does not have OPFS support.`

`(anonymous) @ sqlite3.js:9978
CoroutineExceptionHandlerImpl.kt:11 Gcause: undefinedmessage: "{\"message\":\"sqlite result code 1: no such vfs: opfs\",\"name\":\"Error\"}"name: "G"stack: "G: {\"message\":\"sqlite result code 1: no such vfs: opfs\",\"name\":\"Error\"}\n    at R.tx (https://dellisd.github.io/sqldelight-sqlite-wasm/sqldelight-sqlite-wasm.js:1:315503)\n    at R.handleEvent (https://dellisd.github.io/sqldelight-sqlite-wasm/sqldelight-sqlite-wasm.js:1:315653)"[[Prototype]]: Errorconstructor: ƒ G(t)[[Prototype]]: Object
fe @ CoroutineExceptionHandlerImpl.kt:11`

**Comment by Burtan** [comment]
Ah, I guess OPFS is currently only available on a small subset of browsers.

**Comment by dellisd** [comment]
Ah yes, part of the issue is that only a few browsers currently support OPFS to the degree that SQLite needs (I think Chromium-based ones are the only ones to date).

The other problem is that OPFS requires the site/scripts to be loaded with certain headers, which unfortunately can't be done on GitHub pages so that live demo will never work. I'll probably set up a proper live demo eventually, but for now I'm going to remove that link.

**Comment by chrisjenx** [comment]
Chromium-derived browsers released since approximately mid-2022. As of v108 (November 2022) some OPFS APIs changed from asynchronous to synchronous, which affects how client code (i.e. this library) has to deal with them.
Firefox v111 (March 2023) and later
Safari 16.4 (March 2023) and later

**Comment by niolasdev** [comment]
Unfortunately doesn't work for me, even in browsers supporting OPFS

**Comment by Joe3112** [comment]
I have implemented the solution in my project and it works for me, tested on chrome.

**Comment by edawn** [comment]
Like @dellisd stated above, the reason why the example does not work, is missing response headers from the HTTP server when requesting https://dellisd.github.io/sqldelight-sqlite-wasm/

But one can still make the example work by overriding the headers in the devtools:
https://developer.chrome.com/docs/devtools/overrides

Here's more information about the required headers:
https://sqlite.org/wasm/doc/trunk/persistence.md#coop-coep
